import { CONFIG } from "./config.js";

export class CollectorSystem {
  constructor(scene){this.scene=scene;this.collected=[];this.trayMaterials=[];this.slotMarkers=[];this.ensureHud();this.createTrayVisuals();}
  ensureHud(){if(document.getElementById("upayBoard"))return;const app=document.getElementById("app")||document.body,board=document.createElement("div");board.id="upayBoard";board.style.cssText="position:absolute;right:10px;top:68px;z-index:12;display:flex;flex-direction:column;gap:8px;pointer-events:none";board.innerHTML=`<div id="upay1" style="min-width:118px;padding:10px 12px;border-radius:13px;background:rgba(6,18,31,.72);border:1px solid rgba(255,255,255,.18);color:#fff;text-align:center;box-shadow:0 6px 18px rgba(0,0,0,.18);transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease"><div style="font-size:13px;font-weight:800;letter-spacing:.12em;opacity:.85">УПАЙ 1</div><div id="upay1Count" style="font-size:20px;font-weight:900;margin-top:3px">0/3</div></div><div id="upay2" style="min-width:118px;padding:10px 12px;border-radius:13px;background:rgba(6,18,31,.72);border:1px solid rgba(255,255,255,.18);color:#fff;text-align:center;box-shadow:0 6px 18px rgba(0,0,0,.18);transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease"><div style="font-size:13px;font-weight:800;letter-spacing:.12em;opacity:.85">УПАЙ 2</div><div id="upay2Count" style="font-size:20px;font-weight:900;margin-top:3px">0/3</div></div>`;app.appendChild(board);}
  createTrayVisuals(){if(this.scene.getMeshByName("upayTray1"))return;const makeTray=(name,x)=>{const tray=BABYLON.MeshBuilder.CreateBox(name,{width:2.65,height:.035,depth:1.02},this.scene);tray.position.set(x,.025,3.75);tray.isPickable=false;const mat=new BABYLON.StandardMaterial(`${name}Mat`,this.scene);mat.diffuseColor=new BABYLON.Color3(.08,.20,.27);mat.emissiveColor=new BABYLON.Color3(.02,.06,.08);mat.alpha=.72;tray.material=mat;this.trayMaterials.push(mat);};makeTray("upayTray1",-1.55);makeTray("upayTray2",1.55);for(let i=0;i<6;i++){const p=this.getSlot(i),marker=BABYLON.MeshBuilder.CreateCylinder(`upaySlot${i+1}`,{diameter:.44,height:.012,tessellation:32},this.scene);marker.position.set(p.x,.055,p.z);marker.isPickable=false;const mm=new BABYLON.StandardMaterial(`upaySlotMat${i+1}`,this.scene);mm.diffuseColor=new BABYLON.Color3(.35,.52,.58);mm.emissiveColor=new BABYLON.Color3(.04,.09,.11);mm.alpha=.28;marker.material=mm;this.slotMarkers.push(marker);}}
  reset(){this.collected=[];for(const marker of this.slotMarkers)marker.setEnabled(true);for(const mat of this.trayMaterials)mat.emissiveColor.copyFromFloats(.02,.06,.08);this.updateHud();}
  getSlot(index){const slots=[new BABYLON.Vector3(-2.10,.30,3.75),new BABYLON.Vector3(-1.55,.30,3.75),new BABYLON.Vector3(-1.00,.30,3.75),new BABYLON.Vector3(1.00,.30,3.75),new BABYLON.Vector3(1.55,.30,3.75),new BABYLON.Vector3(2.10,.30,3.75)];return slots[Math.min(index,slots.length-1)].clone();}
  collect(piece,onDone,hitDirection=null){if(!piece||piece.metadata?.collected){onDone?.(null);return false;}const index=this.collected.length;if(index>=6){onDone?.({total:6,unit:2,unitComplete:true,allComplete:true});return false;}piece.metadata.collected=true;piece.metadata.label?.dispose?.();piece.metadata.label=null;piece.isPickable=false;for(const child of piece.getChildMeshes?.()||[])child.isPickable=false;const body=piece.metadata?.aggregate?.body;try{body?.setLinearVelocity(BABYLON.Vector3.Zero());body?.setAngularVelocity(BABYLON.Vector3.Zero());body?.setMotionType(BABYLON.PhysicsMotionType.ANIMATED);}catch(_){}const start=piece.getAbsolutePosition().clone(),end=this.getSlot(index),startQ=piece.rotationQuaternion?piece.rotationQuaternion.clone():BABYLON.Quaternion.FromEulerAngles(piece.rotation.x,piece.rotation.y,piece.rotation.z),endQ=BABYLON.Quaternion.FromEulerAngles(0,0,Math.PI/2);piece.metadata.aggregate?.dispose?.();piece.metadata.aggregate=null;piece.position.copyFrom(start);
    let dir=hitDirection?hitDirection.clone():new BABYLON.Vector3(start.x,0,start.z);dir.y=0;if(dir.length()<.05)dir=new BABYLON.Vector3(1,0,0);dir.normalize();const exit=this.computeExitPoint(start,dir);const t0=performance.now(),exitDuration=390,trayDuration=560,totalDuration=exitDuration+trayDuration;
    const observer=this.scene.onBeforeRenderObservable.add(()=>{const elapsed=performance.now()-t0;if(elapsed<=exitDuration){const t=Math.min(1,elapsed/exitDuration),e=1-Math.pow(1-t,3),p=BABYLON.Vector3.Lerp(start,exit,e);p.y+=Math.sin(Math.PI*t)*.18;piece.position.copyFrom(p);piece.rotationQuaternion=BABYLON.Quaternion.Slerp(startQ,BABYLON.Quaternion.RotationAxis(BABYLON.Axis.Z,1.2).multiply(startQ),e);return;}const t=Math.min(1,(elapsed-exitDuration)/trayDuration),e=1-Math.pow(1-t,3),p=BABYLON.Vector3.Lerp(exit,end,e);p.y+=Math.sin(Math.PI*t)*.72;piece.position.copyFrom(p);piece.rotationQuaternion=BABYLON.Quaternion.Slerp(startQ,endQ,e);if(elapsed>=totalDuration){this.scene.onBeforeRenderObservable.remove(observer);piece.position.copyFrom(end);piece.rotationQuaternion.copyFrom(endQ);this.slotMarkers[index]?.setEnabled(false);this.collected.push(piece);this.updateHud();const total=this.collected.length,unit=total<=3?1:2,unitComplete=total===3||total===6;if(unitComplete)this.celebrateUnit(unit);onDone?.({total,unit,unitComplete,allComplete:total===6,progressInUnit:total<=3?total:total-3});}});return true;}
  computeExitPoint(start,dir){const a=CONFIG.playArea,halfW=a.width/2, minZ=(a.centerZ??0)-a.depth/2,maxZ=(a.centerZ??0)+a.depth/2;let tx=Infinity,tz=Infinity;if(Math.abs(dir.x)>.001)tx=((dir.x>0?halfW:-halfW)-start.x)/dir.x;if(Math.abs(dir.z)>.001)tz=((dir.z>0?maxZ:minZ)-start.z)/dir.z;let t=Math.min(tx>0?tx:Infinity,tz>0?tz:Infinity);if(!Number.isFinite(t))t=1.2;const outside=.50;return new BABYLON.Vector3(start.x+dir.x*(t+outside),Math.max(.30,start.y),start.z+dir.z*(t+outside));}
  celebrateUnit(unit){const mat=this.trayMaterials[unit-1],hud=document.getElementById(`upay${unit}`),start=performance.now(),duration=720;if(hud){hud.style.transform="scale(1.08)";window.setTimeout(()=>{hud.style.transform="scale(1)";},220);}if(!mat)return;const observer=this.scene.onBeforeRenderObservable.add(()=>{const t=Math.min(1,(performance.now()-start)/duration),pulse=Math.sin(Math.PI*t);mat.emissiveColor.copyFromFloats(.02+pulse*.34,.06+pulse*.25,.08+pulse*.08);if(t>=1){this.scene.onBeforeRenderObservable.remove(observer);mat.emissiveColor.copyFromFloats(.13,.11,.03);}});}
  updateHud(){this.ensureHud();const total=this.collected.length,one=Math.min(total,3),two=Math.max(0,Math.min(total-3,3)),upay1=document.getElementById("upay1Count"),upay2=document.getElementById("upay2Count"),tray1=document.getElementById("upay1"),tray2=document.getElementById("upay2");if(upay1)upay1.textContent=one>=3?"1 УПАЙ":`${one}/3`;if(upay2)upay2.textContent=two>=3?"2 УПАЙ":`${two}/3`;if(tray1){tray1.style.borderColor=one>=3?"#e7c36a":"rgba(255,255,255,.18)";tray1.style.boxShadow=one>=3?"0 0 20px rgba(231,195,106,.52)":"0 6px 18px rgba(0,0,0,.18)";}if(tray2){tray2.style.borderColor=two>=3?"#e7c36a":"rgba(255,255,255,.18)";tray2.style.boxShadow=two>=3?"0 0 20px rgba(231,195,106,.52)":"0 6px 18px rgba(0,0,0,.18)";}}
}
